package com.clps.mms.sm.dao;

import java.util.List;

import com.clps.mms.sm.pojo.Account;
import com.clps.mms.sm.vo.AccountVo;
import com.clps.mms.util.paging.PagingVO;
/**
 * 
		* @desc: Account的接口类
		* @author: sea.zhang
		* @createTime: 2018年5月21日 上午9:05:47
		* @version: v1.0
 */
public interface AccountMapper {
	
    /**删除账户的信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_account
     *
     * @mbg.generated Fri May 04 11:24:14 GMT+08:00 2018
     */
    int deleteAccountInfo(String account);

    /**新增账户的信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_account
     * @mbg.generated Fri May 04 11:24:14 GMT+08:00 2018
     */
    int addAccountInfo(Account record);

    
    /**查询账户的信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_account
     * @mbg.generated Fri May 04 11:24:14 GMT+08:00 2018
     */
    List<Account> queryAccountInfoById(String account);
    
    /**
            * 查询所有账户的信息
    		* @author: sea
    		* @createTime: 2018年5月8日 下午2:25:50
    		* @return List<Account> 账户列表
     */
    List<Account> queryAllAccountInfo();
    
    /**
            * 模糊查询账户的信息
    		* @author: sea。zhang
    		* @createTime: 2018年5月8日 下午2:26:33
    		* @param account 账户名称
    		* @return List<Account>
     */
    List<Account>  queryAccountInfoByLike(String account);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_account
     * @mbg.generated Fri May 04 11:24:14 GMT+08:00 2018
     */
    int updateAccountInfo(Account account);
    
    /**
            * 将账户相关的id转换为相应的名称
    		* @author: sea。zhang
    		* @createTime: 2018年5月8日 下午2:28:19
    		* @param account 账户
    		* @return VO
     */
    public AccountVo accountDisplay(Account account);
    
    public int queryAccountCount();
    
    public List<Account> findByPaging(PagingVO VO);
    
}