package com.clps.mms.sm.pojo;

import java.io.Serializable;
import java.sql.Timestamp;
/**
  * 
 		* @desc: Account类
		* @author: sea.zhang
		* @createTime: 2018年5月21日 下午1:49:11
		* @version: v1.0
 */
public class Account implements Serializable{
		
	private static final long serialVersionUID = 1L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_pass
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_mail
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_position_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountPositionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_department_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountDepartmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_role_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_company_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountCompanyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_phone
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_telephone
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountTelephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_comment
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountComment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_created_datetime
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private  Timestamp accountCreatedDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_created_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountCreatedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_updated_datetime
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Timestamp accountUpdatedDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_updated_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer accountUpdatedName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.is_visible
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private Integer isVisible;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sm_account.account_default
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	private String accountDefault;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_id
	 * @return  the value of sm_account.account_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	
	public Account(Integer accountId, String accountName, String account, String accountPass, String accountMail,
			Integer accountPositionId, Integer accountDepartmentId, Integer accountRoleId, Integer accountCompanyId,
			String accountPhone, String accountTelephone, String accountComment,  Timestamp accountCreatedDatetime,
			Integer accountCreatedName,  Timestamp accountUpdatedDatetime, Integer accountUpdatedName, Integer isVisible,
			String accountDefault) {
		super();
		this.accountId = accountId;
		this.accountName = accountName;
		this.account = account;
		this.accountPass = accountPass;
		this.accountMail = accountMail;
		this.accountPositionId = accountPositionId;
		this.accountDepartmentId = accountDepartmentId;
		this.accountRoleId = accountRoleId;
		this.accountCompanyId = accountCompanyId;
		this.accountPhone = accountPhone;
		this.accountTelephone = accountTelephone;
		this.accountComment = accountComment;
		this.accountCreatedDatetime = accountCreatedDatetime;
		this.accountCreatedName = accountCreatedName;
		this.accountUpdatedDatetime = accountUpdatedDatetime;
		this.accountUpdatedName = accountUpdatedName;
		this.isVisible = isVisible;
		this.accountDefault = accountDefault;
	}
	
	
	
	public Account() {
		super();		
	}



	public Integer getAccountId() {
		return accountId;
	}

	

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_id
	 * @param accountId  the value for sm_account.account_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_name
	 * @return  the value of sm_account.account_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_name
	 * @param accountName  the value for sm_account.account_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account
	 * @return  the value of sm_account.account
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account
	 * @param account  the value for sm_account.account
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_pass
	 * @return  the value of sm_account.account_pass
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountPass() {
		return accountPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_pass
	 * @param accountPass  the value for sm_account.account_pass
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountPass(String accountPass) {
		this.accountPass = accountPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_mail
	 * @return  the value of sm_account.account_mail
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountMail() {
		return accountMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_mail
	 * @param accountMail  the value for sm_account.account_mail
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountMail(String accountMail) {
		this.accountMail = accountMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_position_id
	 * @return  the value of sm_account.account_position_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getAccountPositionId() {
		return accountPositionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_position_id
	 * @param accountPositionId  the value for sm_account.account_position_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountPositionId(Integer accountPositionId) {
		this.accountPositionId = accountPositionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_department_id
	 * @return  the value of sm_account.account_department_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getAccountDepartmentId() {
		return accountDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_department_id
	 * @param accountDepartmentId  the value for sm_account.account_department_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountDepartmentId(Integer accountDepartmentId) {
		this.accountDepartmentId = accountDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_role_id
	 * @return  the value of sm_account.account_role_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getAccountRoleId() {
		return accountRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_role_id
	 * @param accountRoleId  the value for sm_account.account_role_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountRoleId(Integer accountRoleId) {
		this.accountRoleId = accountRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_company_id
	 * @return  the value of sm_account.account_company_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getAccountCompanyId() {
		return accountCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_company_id
	 * @param accountCompanyId  the value for sm_account.account_company_id
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountCompanyId(Integer accountCompanyId) {
		this.accountCompanyId = accountCompanyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_phone
	 * @return  the value of sm_account.account_phone
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountPhone() {
		return accountPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_phone
	 * @param accountPhone  the value for sm_account.account_phone
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountPhone(String accountPhone) {
		this.accountPhone = accountPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_telephone
	 * @return  the value of sm_account.account_telephone
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountTelephone() {
		return accountTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_telephone
	 * @param accountTelephone  the value for sm_account.account_telephone
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountTelephone(String accountTelephone) {
		this.accountTelephone = accountTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_comment
	 * @return  the value of sm_account.account_comment
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountComment() {
		return accountComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_comment
	 * @param accountComment  the value for sm_account.account_comment
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountComment(String accountComment) {
		this.accountComment = accountComment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_created_datetime
	 * @return  the value of sm_account.account_created_datetime
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public  Timestamp getAccountCreatedDatetime() {
		return accountCreatedDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_created_datetime
	 * @param accountCreatedDatetime  the value for sm_account.account_created_datetime
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountCreatedDatetime( Timestamp accountCreatedDatetime) {
		this.accountCreatedDatetime = accountCreatedDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_created_name
	 * @return  the value of sm_account.account_created_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getAccountCreatedName() {
		return accountCreatedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_created_name
	 * @param accountCreatedName  the value for sm_account.account_created_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountCreatedName(Integer accountCreatedName) {
		this.accountCreatedName = accountCreatedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_updated_datetime
	 * @return  the value of sm_account.account_updated_datetime
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public  Timestamp getAccountUpdatedDatetime() {
		return accountUpdatedDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_updated_datetime
	 * @param accountUpdatedDatetime  the value for sm_account.account_updated_datetime
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountUpdatedDatetime(Timestamp accountUpdatedDatetime) {
		this.accountUpdatedDatetime = accountUpdatedDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_updated_name
	 * @return  the value of sm_account.account_updated_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getAccountUpdatedName() {
		return accountUpdatedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_updated_name
	 * @param accountUpdatedName  the value for sm_account.account_updated_name
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountUpdatedName(Integer accountUpdatedName) {
		this.accountUpdatedName = accountUpdatedName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.is_visible
	 * @return  the value of sm_account.is_visible
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public Integer getIsVisible() {
		return isVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.is_visible
	 * @param isVisible  the value for sm_account.is_visible
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setIsVisible(Integer isVisible) {
		this.isVisible = isVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sm_account.account_default
	 * @return  the value of sm_account.account_default
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public String getAccountDefault() {
		return accountDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sm_account.account_default
	 * @param accountDefault  the value for sm_account.account_default
	 * @mbg.generated  Fri May 04 11:24:14 GMT+08:00 2018
	 */
	public void setAccountDefault(String accountDefault) {
		this.accountDefault = accountDefault;
	}

	@Override
	public String toString() {
		return "Account [accountId=" + accountId + ", accountName=" + accountName + ", account=" + account
				+ ", accountPass=" + accountPass + ", accountMail=" + accountMail + ", accountPositionId="
				+ accountPositionId + ", accountDepartmentId=" + accountDepartmentId + ", accountRoleId="
				+ accountRoleId + ", accountCompanyId=" + accountCompanyId + ", accountPhone=" + accountPhone
				+ ", accountTelephone=" + accountTelephone + ", accountComment=" + accountComment
				+ ", accountCreatedDatetime=" + accountCreatedDatetime + ", accountCreatedName=" + accountCreatedName
				+ ", accountUpdatedDatetime=" + accountUpdatedDatetime + ", accountUpdatedName=" + accountUpdatedName
				+ ", isVisible=" + isVisible + ", accountDefault=" + accountDefault + "]";
	}

	
}